function page = build_page_control(parent, theme, meas)
page = uipanel(parent, 'Title', '', 'BackgroundColor', theme.C_bg, ...
    'Position', [0 0 1155 700], 'BorderType', 'none');

idnPanel = uipanel(page, 'Title', '设备信息', 'FontWeight', 'bold', ...
    'BackgroundColor', theme.C_panel, 'Position', [15 545 1125 140]);
uitextarea(idnPanel, 'Position', [15 15 1095 95], 'Editable', 'off', ...
    'BackgroundColor', theme.C_logBg, 'Value', {'仪器信息显示区'});

measPanel = uipanel(page, 'Title', '测量参数设置', 'FontWeight', 'bold', ...
    'BackgroundColor', theme.C_panel, 'Position', [15 280 1125 240]);
uilabel(measPanel, 'Text', sprintf('默认参数: %s, F=%gHz, V=%gVrms', meas.param, meas.freq, meas.level), ...
    'Position', [20 160 600 24], 'FontColor', theme.C_subtext);
end
