function page = build_page_settings(parent, theme, cfg)
page = uipanel(parent, 'Title', '', 'BackgroundColor', theme.C_bg, ...
    'Position', [0 0 1155 700], 'BorderType', 'none');

panel = uipanel(page, 'Title', '', 'BackgroundColor', theme.C_panel, ...
    'Position', [15 15 1125 670]);
uilabel(panel, 'Text', '软件设置', 'Position', [20 620 180 28], ...
    'FontSize', 18, 'FontWeight', 'bold', 'FontColor', theme.C_title);
uilabel(panel, 'Text', sprintf('默认 IP: %s  端口: %d', cfg.ip, cfg.port), ...
    'Position', [24 545 300 22], 'FontColor', theme.C_subtext);
end
