function page = build_page_acq(parent, theme, cfg)
page = uipanel(parent, 'Title', '', 'BackgroundColor', theme.C_bg, ...
    'Position', [0 0 1155 700], 'BorderType', 'none');

top = uipanel(page, 'Title', '采样设置', 'FontWeight', 'bold', ...
    'BackgroundColor', theme.C_panel, 'Position', [15 490 1125 195]);
uilabel(top, 'Text', sprintf('默认间隔: %.2fs | 默认时长: %.1fs', cfg.interval, cfg.duration), ...
    'Position', [20 130 420 22], 'FontColor', theme.C_subtext);

logPanel = uipanel(page, 'Title', '采样日志', 'FontWeight', 'bold', ...
    'BackgroundColor', theme.C_panel, 'Position', [15 15 1125 450]);
txtLog = uitextarea(logPanel, 'Position', [15 15 1095 405], 'Editable', 'off', ...
    'BackgroundColor', theme.C_logBg, 'Value', {'程序启动完成。'});

page.UserData = struct('txtLog', txtLog);
end
