function uiStruct = build_main_layout(theme, brand, cfg)
% 创建主布局与公共控件

    mainFig = uifigure('Name', ['E4980AL Control Center - ' brand.companyName], ...
        'Position', [70 40 1420 860], 'Color', theme.C_bg);

    navPanel = uipanel(mainFig, 'BackgroundColor', theme.C_nav, ...
        'Position', [15 15 220 830], 'BorderType', 'none');
    headerPanel = uipanel(mainFig, 'BackgroundColor', theme.C_panel, ...
        'Position', [250 775 1155 70]);
    contentPanel = uipanel(mainFig, 'BackgroundColor', theme.C_bg, ...
        'Position', [250 65 1155 700], 'BorderType', 'none');
    statusPanel = uipanel(mainFig, 'BackgroundColor', theme.C_panel, ...
        'Position', [250 15 1155 40]);

    hdrTitle = uilabel(headerPanel, 'Text', 'home', ...
        'Position', [24 22 180 26], 'FontSize', 18, 'FontWeight', 'bold', ...
        'FontColor', theme.C_title);

    btnReadIDN = uibutton(headerPanel, 'push', 'Text', '读取 IDN', ...
        'Position', [920 18 100 34], 'BackgroundColor', theme.C_primarySoft, ...
        'FontColor', theme.C_title);
    btnConnect = uibutton(headerPanel, 'push', 'Text', '连接', ...
        'Position', [1030 18 50 34], 'BackgroundColor', theme.C_primary, ...
        'FontColor', [1 1 1], 'FontWeight', 'bold');
    btnDisconnect = uibutton(headerPanel, 'push', 'Text', '断开', ...
        'Position', [1090 18 50 34], 'BackgroundColor', theme.C_danger, ...
        'FontColor', [1 1 1], 'FontWeight', 'bold');

    navLamp = uilamp(navPanel, 'Position', [22 600 18 18], 'Color', theme.C_danger);
    navStatus = uilabel(navPanel, 'Text', '未连接', 'Position', [50 597 130 22], ...
        'FontWeight', 'bold', 'FontColor', theme.C_navText);

    btnHome = uibutton(navPanel, 'push', 'Text', '首页', ...
        'Position', [20 545 180 40], 'BackgroundColor', theme.C_navSoft, ...
        'FontColor', theme.C_navText, 'FontWeight', 'bold');
    btnControl = uibutton(navPanel, 'push', 'Text', '控制台', ...
        'Position', [20 495 180 40], 'BackgroundColor', theme.C_navSoft, ...
        'FontColor', theme.C_navText, 'FontWeight', 'bold');
    btnAcq = uibutton(navPanel, 'push', 'Text', '采样与数据', ...
        'Position', [20 445 180 40], 'BackgroundColor', theme.C_navSoft, ...
        'FontColor', theme.C_navText, 'FontWeight', 'bold');
    btnSettings = uibutton(navPanel, 'push', 'Text', '设置', ...
        'Position', [20 395 180 40], 'BackgroundColor', theme.C_navSoft, ...
        'FontColor', theme.C_navText, 'FontWeight', 'bold');
    btnAbout = uibutton(navPanel, 'push', 'Text', '关于', ...
        'Position', [20 345 180 40], 'BackgroundColor', theme.C_navSoft, ...
        'FontColor', theme.C_navText, 'FontWeight', 'bold');

    statusLeft = uilabel(statusPanel, 'Text', '状态：未连接', ...
        'Position', [16 8 240 22], 'FontWeight', 'bold', 'FontColor', theme.C_subtext);
    statusMid = uilabel(statusPanel, 'Text', sprintf('IP: %s   端口: %d', cfg.ip, cfg.port), ...
        'Position', [300 8 280 22], 'FontColor', theme.C_subtext);
    statusRight = uilabel(statusPanel, 'Text', brand.companyName, ...
        'Position', [700 8 420 22], 'HorizontalAlignment', 'right', ...
        'FontColor', theme.C_subtext);

    uiStruct = struct('mainFig', mainFig, 'navPanel', navPanel, 'headerPanel', headerPanel, ...
        'contentPanel', contentPanel, 'statusPanel', statusPanel, 'hdrTitle', hdrTitle, ...
        'btnReadIDN', btnReadIDN, 'btnConnect', btnConnect, 'btnDisconnect', btnDisconnect, ...
        'navLamp', navLamp, 'navStatus', navStatus, 'btnHome', btnHome, 'btnControl', btnControl, ...
        'btnAcq', btnAcq, 'btnSettings', btnSettings, 'btnAbout', btnAbout, ...
        'statusLeft', statusLeft, 'statusMid', statusMid, 'statusRight', statusRight, ...
        'txtIDN', [], 'txtLog', []);
end
