function page = build_page_about(parent, theme, brand)
page = uipanel(parent, 'Title', '', 'BackgroundColor', theme.C_bg, ...
    'Position', [0 0 1155 700], 'BorderType', 'none');

box = uipanel(page, 'Title', '', 'BackgroundColor', theme.C_panel, ...
    'Position', [15 15 1125 670]);
uilabel(box, 'Text', '关于本软件', 'Position', [24 620 180 30], ...
    'FontSize', 20, 'FontWeight', 'bold', 'FontColor', theme.C_title);
uilabel(box, 'Text', brand.companyName, 'Position', [24 580 560 28], ...
    'FontSize', 14, 'FontWeight', 'bold', 'FontColor', theme.C_subtext);
uilabel(box, 'Text', brand.brandTagline, 'Position', [24 554 560 22], ...
    'FontSize', 11, 'FontColor', theme.C_subtext);
end
